/*
 * foreign_jounarl User
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/riy0/foreign_journal/go"
)

func main() {
	log.Printf("Server started")

	AddUserApiService := openapi.NewAddUserApiService()
	AddUserApiController := openapi.NewAddUserApiController(AddUserApiService)

	UsersApiService := openapi.NewUsersApiService()
	UsersApiController := openapi.NewUsersApiController(UsersApiService)

	router := openapi.NewRouter(AddUserApiController, UsersApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
