openapi: "3.0.0"
info:
  version: 1.0.0
  title: foreign_jounarl User
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/
paths:
  /users:
    get:
      summary: get all user information
      tags:
        - users
      parameters: []
      responses:
        "200":
          description: return user information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /user/add:
    post:
      summary: create a new user
      tags:
        - addUser
      parameters: []
      requestBody:
        description: user to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
            example:
              name: hoge
              mail: hoge@fuga
              password: hogehgoe
      responses:
        "201":
          description: success

components:
  schemas:
    User:
      required:
        - name
        - mail
        - password
      properties:
        id:
          type: string
        name:
          type: string
        mail:
          type: string
        password:
          type: string
