/*
 * foreign_jounarl User
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// AddUserApiRouter defines the required methods for binding the api requests to a responses for the AddUserApi
// The AddUserApiRouter implementation should parse necessary information from the http request, 
// pass the data to a AddUserApiServicer to perform the required actions, then write the service results to the http response.
type AddUserApiRouter interface { 
	UserAddPost(http.ResponseWriter, *http.Request)
}
// UsersApiRouter defines the required methods for binding the api requests to a responses for the UsersApi
// The UsersApiRouter implementation should parse necessary information from the http request, 
// pass the data to a UsersApiServicer to perform the required actions, then write the service results to the http response.
type UsersApiRouter interface { 
	UsersGet(http.ResponseWriter, *http.Request)
}


// AddUserApiServicer defines the api actions for the AddUserApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type AddUserApiServicer interface { 
	UserAddPost(User) (interface{}, error)
}


// UsersApiServicer defines the api actions for the UsersApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type UsersApiServicer interface { 
	UsersGet() (interface{}, error)
}
