/*
 * foreign_jounarl User
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// AddUserApiService is a service that implents the logic for the AddUserApiServicer
// This service should implement the business logic for every endpoint for the AddUserApi API. 
// Include any external packages or services that will be required by this service.
type AddUserApiService struct {
}

// NewAddUserApiService creates a default api service
func NewAddUserApiService() AddUserApiServicer {
	return &AddUserApiService{}
}

// UserAddPost - create a new user
func (s *AddUserApiService) UserAddPost(user User) (interface{}, error) {
	// TODO - update UserAddPost with the required logic for this service method.
	// Add api_add_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UserAddPost' not implemented")
}
