openapi: 3.0.0
info:
  license:
    name: MIT
  title: foreign_jounarl User
  version: 1.0.0
servers:
- url: http://localhost:8080/api/
paths:
  /users:
    get:
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: return user information
      summary: get all user information
      tags:
      - users
  /user/add:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              name: hoge
              mail: hoge@fuga
              password: hogehgoe
            schema:
              $ref: '#/components/schemas/User'
        description: user to create
      responses:
        201:
          description: success
      summary: create a new user
      tags:
      - addUser
components:
  schemas:
    User:
      example:
        password: password
        mail: mail
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        mail:
          type: string
        password:
          type: string
      required:
      - mail
      - name
      - password
